Cypress.Commands.add('login', (url=`${Cypress.env('host')}`, auth=`${Cypress.env('auth')}`, user=`${Cypress.env('username')}`, password=`${Cypress.env('password')}`) => {
    cy.visit(url)
    cy.origin(auth, { args: { username: user, password: password } }, ({ username, password }) => {
        cy.get(':nth-child(1) > .pf-c-button', { timeout: 60000 })
        cy.contains('kube:admin').click()
        cy.get('#inputUsername').should('exist')
        cy.get('#inputUsername').should('be.visible')
        cy.get('#inputPassword').should('exist')
        cy.get('#inputPassword').should('be.visible')
        cy.get('#inputUsername').type(username)
        cy.get('#inputPassword').type(password)
        cy.get('#inputUsername').should('have.value', username)
        cy.get('#inputPassword').should('have.value', password)
        cy.contains('button', 'Log in').click()
      })
    cy.get('.pf-v5-c-modal-box__close > .pf-v5-c-button', { timeout: 60000 })
    cy.get('.pf-v5-c-modal-box__close > .pf-v5-c-button').should('be.visible')
    cy.get('.pf-v5-c-modal-box__close > .pf-v5-c-button').click()
    cy.url().should('include', `${Cypress.env('host')}`)
})
Cypress.Commands.add('deviceApproval', () => {
    cy.get('#nav-toggle').should('exist')
    cy.get('#nav-toggle').click()
    cy.contains('Edge Management').click()
    cy.contains('Devices').click()
    cy.get(':nth-child(1) > .pf-v5-l-flex > :nth-child(1) > .pf-v5-c-title').contains('Devices pending approval')
    cy.get('[data-label="Approve"] > .pf-v5-c-button').should('exist')
    cy.get('[data-label="Approve"] > .pf-v5-c-button').should('be.visible')
    cy.get('[data-label="Approve"] > .pf-v5-c-button').click()
    cy.get('#rich-validation-field-deviceAlias').should('be.visible')
    cy.get('#rich-validation-field-deviceAlias').type('test-device')
    cy.get('#rich-validation-field-deviceAlias').should('have.value', 'test-device')
    cy.get('.pf-v5-c-form__actions > .pf-m-primary').should('be.visible')
    cy.get('.pf-v5-c-form__actions > .pf-m-primary').click()
    cy.get('[data-label="Device status"]', { timeout: 50000 }).should('contain', 'Online')
})
Cypress.Commands.add('editDevice', (img=`${Cypress.env('image')}`) => {
    cy.get('#nav-toggle').should('exist')
    cy.get('#nav-toggle').click()
    cy.contains('Edge Management').click()
    cy.contains('Devices').click()
    cy.get('a > .fctl-resource-link__text').contains('test-device')
    cy.get('.pf-v5-c-table__action > .pf-v5-c-menu-toggle').click()
    cy.contains('Edit device configurations').click()
    cy.get('#rich-validation-field-deviceAlias').should('be.visible')
    cy.get('#rich-validation-field-deviceAlias').should('have.value', 'test-device')
    cy.get('#rich-validation-field-deviceAlias').clear()
    cy.get('#rich-validation-field-deviceAlias').type('test-device-edited')
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('#textfield-osImage').should('be.visible')
    cy.get('#textfield-osImage').type(img)
    cy.get('#textfield-osImage').should('have.value', 'quay.io/sdelacru/flightctl-centos:v1')
    wizardFooter.getNextButton().click()
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('.pf-v5-c-title > .pf-v5-l-grid > .pf-m-6-col-on-md').should('contain', 'test-device-edited')
})
Cypress.Commands.add('decommissionDevice', () => {
    cy.get('#nav-toggle').should('exist')
    cy.get('#nav-toggle').click()
    cy.contains('Edge Management').click()
    cy.contains('Devices').click()
    cy.get('.pf-v5-c-table__tbody > .pf-v5-c-table__tr > .pf-v5-c-table__check > label > input').should('be.visible')
    cy.get('.pf-v5-c-table__tbody > .pf-v5-c-table__tr > .pf-v5-c-table__check > label > input').click()
    cy.get('#devices-toolbar > :nth-child(1) > .pf-v5-c-toolbar__content-section > :nth-child(3) > .pf-v5-c-button').should('be.visible')
    cy.get('#devices-toolbar > :nth-child(1) > .pf-v5-c-toolbar__content-section > :nth-child(3) > .pf-v5-c-button').click()
    cy.get('.pf-m-danger').should('be.visible')
    cy.get('.pf-m-danger').click()
    cy.get('.pf-v5-c-table__thead > .pf-v5-c-table__tr > .pf-v5-c-table__check > label > input').should('be.visible')
    cy.get('.pf-v5-c-table__thead > .pf-v5-c-table__tr > .pf-v5-c-table__check > label > input').click()
    cy.get('.pf-v5-c-toolbar__group > :nth-child(3) > .pf-v5-c-button').should('be.visible')
    cy.get('.pf-v5-c-toolbar__group > :nth-child(3) > .pf-v5-c-button').click()
    cy.get('.pf-m-danger').should('be.visible')
    cy.get('.pf-m-danger').click()
    cy.get('.pf-v5-c-switch__toggle').should('be.visible')
    cy.get('.pf-v5-c-switch__toggle').click()

})
Cypress.Commands.add('createFleet', (img = `${Cypress.env('image')}`) => {
    cy.get('#nav-toggle').click()
    cy.contains('Edge Management').click()
    cy.contains('Fleets').click()
    cy.get(':nth-child(2) > .pf-v5-l-split > :nth-child(1) > .pf-v5-c-button').should('exist')
    cy.get(':nth-child(2) > .pf-v5-l-split > :nth-child(1) > .pf-v5-c-button').should('be.visible')
    cy.get(':nth-child(2) > .pf-v5-l-split > :nth-child(1) > .pf-v5-c-button').click()
    cy.get('#rich-validation-field-name').should('be.visible')
    cy.get('#rich-validation-field-name').type('test-fleet')
    cy.get('#rich-validation-field-name').should('have.value', 'test-fleet')
    cy.get('.pf-v5-l-stack__item > .pf-v5-c-label-group > .pf-v5-c-label-group__main > .pf-v5-c-label-group__list').click()
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('#textfield-osImage').should('be.visible')
    cy.get('#textfield-osImage').type(img)
    cy.get('#textfield-osImage').should('have.value', img)
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('.pf-v5-c-title').should('contain', 'test-fleet')
    cy.get('.pf-v5-c-description-list__text > .pf-v5-l-flex', { timeout: 50000 }).should('contain', 'Valid')
})
Cypress.Commands.add('editFleet', () => {
    cy.get('#nav-toggle').click()
    cy.contains('Edge Management').click()
    cy.contains('Fleets').click()
    cy.get('[data-label="Name"]').contains('test-fleet')
    cy.get('.pf-v5-c-table__action > .pf-v5-c-menu-toggle').click()
    cy.get('[data-label="Name"] > .fctl-resource-link > a > .fctl-resource-link__text').contains('test-fleet')
    cy.get('.pf-v5-c-table__action > .pf-v5-c-menu-toggle').should('be.visible')
    cy.get('.pf-v5-c-table__action > .pf-v5-c-menu-toggle').click()
    cy.get('[data-ouia-component-id="OUIA-Generated-DropdownItem-8"] > .pf-v5-c-menu__item > .pf-v5-c-menu__item-main > .pf-v5-c-menu__item-text').click()
    cy.get(':nth-child(2) > .pf-v5-c-form__group-label > .pf-v5-c-form__label > .pf-v5-c-form__label-text').should('contain', 'Fleet name')
    cy.get('.pf-v5-c-form__group-control > .pf-v5-c-label-group > .pf-v5-c-label-group__main > .pf-v5-c-label-group__list > .pf-v5-c-label-group__list-item > .pf-v5-c-button').click()
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('.pf-v5-c-title').should('contain', 'test-fleet')
})
Cypress.Commands.add('deleteFleet', () => {
    cy.get('#nav-toggle').click()
    cy.contains('Edge Management').click()
    cy.contains('Fleets').click()
    cy.get('[data-label="Name"]').contains('test-fleet')
    cy.get('.pf-v5-c-table__tbody > .pf-v5-c-table__tr > .pf-v5-c-table__check > label > input').click()
        cy.get('#pf-random-id-63 > :nth-child(1) > .pf-v5-c-toolbar__content-section > :nth-child(3) > .pf-v5-c-button').click()
        cy.get('.pf-m-danger').should('be.visible')
    cy.get('.pf-m-danger').click()
})
Cypress.Commands.add('importFleet', () => {
    cy.get('#nav-toggle').click()
    cy.contains('Edge Management').click()      
    cy.contains('Fleets').click()
    cy.get(':nth-child(2) > .pf-v5-l-split > :nth-child(2) > .pf-v5-c-button').should('exist')
    cy.get(':nth-child(2) > .pf-v5-l-split > :nth-child(2) > .pf-v5-c-button').should('be.visible')
    cy.get(':nth-child(2) > .pf-v5-l-split > :nth-child(2) > .pf-v5-c-button').click()
    cy.get('#rich-validation-field-name').type('test-fleet')
    cy.get('#textfield-url').type('https://github.com/flightctl/flightctl-demos')
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('#rich-validation-field-resourceSyncs\[0\]\.name').type('test-resource')
    cy.get('#textfield-resourceSyncs\[0\]\.targetRevision').type('main')
    cy.get('#textfield-resourceSyncs\[0\]\.path').type('/demos/basic-nginx-demo/deployment/fleet.yaml')
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('.pf-v5-c-wizard__footer > .pf-m-primary').click()
    cy.get('.pf-v5-c-alert__title').should('contain', 'Importing fleets')
    cy.get('.fctl-resource-link__text', { timeout: 50000 }).should('contain', 'basic-nginx-fleet')
})
Cypress.Commands.add('downloadFile', (os = `${Cypress.env('platform')}`, arch = `${Cypress.env('arch')}`) => {
    cy.get('[data-test="help-dropdown-toggle"]').click()
    cy.contains('Command Line Tools').should('be.visible')
    cy.contains('Command Line Tools').click()
    cy.contains(`Download flightctl for ${os} for ${arch}`).downloadFile()
})
Cypress.Commands.add('createRepository', (repo = `${Cypress.env('repository')}`,revision = `${Cypress.env('revision')}`, resource = `${Cypress.env('resource')}`) => {
    cy.get('#nav-toggle').click()
    cy.contains('Edge Management').click()
    cy.contains('Repositories').click()
    cy.get('.pf-v5-c-toolbar__content-section > :nth-child(2) > .pf-v5-c-button').should('be.visible')
    cy.get('.pf-v5-c-toolbar__content-section > :nth-child(2) > .pf-v5-c-button').click()
    cy.get('#rich-validation-field-name').should('be.visible')
    cy.get('#rich-validation-field-name').type('test-repository')
    cy.get('#rich-validation-field-name').should('have.value', 'test-repository')
    cy.get('#use-resource-syncs').should('be.visible')
    cy.get('#textfield-url').type(repo)
    cy.get('#textfield-url').should('have.value', repo)
    cy.get('.pf-v5-c-form__section').should('be.visible')
    cy.contains('Resource sync name').type('test-resource')
    cy.get('#textfield-resourceSyncs\\[0\\]\\.targetRevision').type(revision)
    cy.get('#textfield-resourceSyncs\\[0\\]\\.path').type(resource)
    cy.get('.pf-v5-c-form__actions > .pf-m-primary').click()
    cy.get('.pf-v5-c-description-list__text > .pf-v5-l-flex > :nth-child(2)', { timeout: 100000 }).should('contain', 'Accessible')
})